# app config
server:
  port: 8081
# spring config
spring:
  jpa:
    database: mysql
  hibernate:
    ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Tehran

#jwt config
  jwt:
    token:
      secret: 4A614E635266556A586E3272357538782F413F4428472B4B6250655367566B59
      validity: 600
      expire: 3600



